namespace Ublux.Communications.Enums;

/// <summary>
///     A problem that occurs with a cloud service
/// </summary>
public enum CloudServiceFlag
{
    /// <summary>
    ///     Unable to save or retrive IdGlobalCounter from disk. If this happens and the counter is incorrect we will have duplicate autogenerated ids
    /// </summary>
    WS_IdGlobalCounter_DiskError,

    /// <summary>
    ///     Unable to store or read last id of items modified on redis
    /// </summary>
    WS_IdStreamModified_DiskError,

    /// <summary>
    ///     Unable to store or read last id of items deleted on redis
    /// </summary>
    WS_IdStreamDeleted_DiskError
}
