namespace Ublux.Communications.Enums;

/// <summary>
///     A problem that occurs with a cloud service
/// </summary>
public enum CloudServiceFlag
{
    /// <summary>
    ///     Unable to save or retrieve IdGlobalCounter from disk. If this happens and the counter is incorrect we will have duplicate autogenerated ids
    /// </summary>
    API_IdGlobalCounter_DiskError,

    /// <summary>
    ///     Unable to store or read last id of items modified on redis
    /// </summary>
    API_IdStreamModified_DiskError,

    /// <summary>
    ///     Unable to store or read last id of items deleted on redis
    /// </summary>
    API_IdStreamDeleted_DiskError,

    /// <summary>
    ///     Unable to convert slave to master
    /// </summary>
    API_UnableToConvertSlaveToMasterRebootRequired
}
